# docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: router_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  router_app:
    build: .
    container_name: router_app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/router_db"
      JWT_SECRET_KEY: "secret"